repos:
  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: unittest
        name: Run Unittests
        entry: python -m pytest
        language: system
        always_run: true
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.6.1'
    hooks:
      - id: mypy
